repositories:
  - repo: https://github.com/hmcts/cnp-plum-frontend.git
    deployment-enabled: true
  - repo: https://github.com/hmcts/cnp-plum-recipes-service.git
    deployment-enabled: true
  - repo: https://github.com/hmcts/cnp-plum-shared-infrastructure.git
    deployment-enabled: true
  - repo: https://github.com/hmcts/cnp-idam-master.git
    deployment-enabled: true
