prod:
  - repo: https://github.com/hmcts/am-shared-infrastructure.git
  - repo: https://github.com/hmcts/aac-manage-case-assignment.git
  - repo: https://github.com/hmcts/bar-api.git
  - repo: https://github.com/hmcts/bar-shared-infrastructure.git
  - repo: https://github.com/hmcts/bar-web.git
  - repo: https://github.com/hmcts/bulk-scan-orchestrator.git
  - repo: https://github.com/hmcts/bulk-scan-processor.git
  - repo: https://github.com/hmcts/bulk-scan-shared-infrastructure.git
  - repo: https://github.com/hmcts/blob-router-service.git
  - repo: https://github.com/hmcts/reform-scan-shared-infra.git
  - repo: https://github.com/hmcts/ccd-admin-web.git
  - repo: https://github.com/hmcts/ccd-admin-web-api.git
  - repo: https://github.com/hmcts/ccd-api-gateway.git
  - repo: https://github.com/hmcts/ccd-case-activity-api.git
  - repo: https://github.com/hmcts/ccd-case-management-web.git
  - repo: https://github.com/hmcts/ccd-case-print-service.git
  - repo: https://github.com/hmcts/ccd-data-store-api.git
  - repo: https://github.com/hmcts/ccd-definition-designer-api.git
  - repo: https://github.com/hmcts/ccd-definition-store-api.git
  - repo: https://github.com/hmcts/ccd-logstash.git
  - repo: https://github.com/hmcts/ccd-elastic-search.git
  - repo: https://github.com/hmcts/ccd-shared-infrastructure.git
  - repo: https://github.com/hmcts/ccd-user-profile-api.git
  - repo: https://github.com/hmcts/ccfr-fees-register-admin-web.git
  - repo: https://github.com/hmcts/ccfr-fees-register-app.git
  - repo: https://github.com/hmcts/ccpay-bubble.git
  - repo: https://github.com/hmcts/ccpay-functions-node.git
  - repo: https://github.com/hmcts/ccpay-payment-app.git
  - repo: https://github.com/hmcts/ccpayfr-shared-infrastructure.git
  - repo: https://github.com/hmcts/cet-shared-infrastructure.git
  - repo: https://github.com/hmcts/cmc-citizen-frontend.git
  - repo: https://github.com/hmcts/cmc-claim-store.git
  - repo: https://github.com/hmcts/cmc-claim-submit-api.git
  - repo: https://github.com/hmcts/cmc-legal-rep-frontend.git
  - repo: https://github.com/hmcts/cmc-shared-infrastructure.git
  - repo: https://github.com/hmcts/cnp-core-compute.git
  - repo: https://github.com/hmcts/cnp-core-infrastructure.git
  - repo: https://github.com/hmcts/cnp-module-api-mgmt.git
  - repo: https://github.com/hmcts/cnp-idam-compute.git
  - repo: https://github.com/hmcts/cnp-idam-master.git
  - repo: https://github.com/hmcts/cnp-idam-storage.git
  - repo: https://github.com/hmcts/cnp-idam-vault.git
  - repo: https://github.com/hmcts/cnp-owaspdependencycheck-database.git
  - repo: https://github.com/hmcts/cnp-pipelinemetrics-database.git
  - repo: https://github.com/hmcts/cnp-rhubarb-frontend.git
  - repo: https://github.com/hmcts/cnp-rhubarb-recipes-service.git
  - repo: https://github.com/hmcts/cnp-rhubarb-shared-infrastructure.git
  - repo: https://github.com/hmcts/ctsc-shared-infrastructure.git
  - repo: https://github.com/hmcts/div-case-data-formatter.git
  - repo: https://github.com/hmcts/div-case-maintenance-service.git
  - repo: https://github.com/hmcts/div-case-orchestration-service.git
  - repo: https://github.com/hmcts/div-decree-absolute-frontend.git
  - repo: https://github.com/hmcts/div-decree-nisi-frontend.git
  - repo: https://github.com/hmcts/div-document-generator-client.git
  - repo: https://github.com/hmcts/div-evidence-management-client-api.git
  - repo: https://github.com/hmcts/div-fees-and-payments-service.git
  - repo: https://github.com/hmcts/div-health-monitor.git
  - repo: https://github.com/hmcts/div-petitioner-frontend.git
  - repo: https://github.com/hmcts/div-respondent-frontend.git
  - repo: https://github.com/hmcts/div-shared-infrastructure.git
  - repo: https://github.com/hmcts/div-validation-service.git
  - repo: https://github.com/hmcts/dm-shared-infrastructure.git
  - repo: https://github.com/hmcts/document-management-store-app.git
  - repo: https://github.com/hmcts/draft-store.git
  - repo: https://github.com/hmcts/ethos-repl-docmosis-service.git
  - repo: https://github.com/hmcts/ecm-consumer.git
  - repo: https://github.com/hmcts/ecm-shared-infrastructure.git
  - repo: https://github.com/hmcts/feature-toggle-api.git
  - repo: https://github.com/hmcts/finrem-case-orchestration-service.git
  - repo: https://github.com/hmcts/finrem-document-generator-client.git
  - repo: https://github.com/hmcts/finrem-evidence-management-client-api.git
  - repo: https://github.com/hmcts/finrem-notification-service.git
  - repo: https://github.com/hmcts/finrem-payment-service.git
  - repo: https://github.com/hmcts/finrem-shared-infrastructure.git
  - repo: https://github.com/hmcts/fpl-ccd-configuration.git
  - repo: https://github.com/hmcts/ia-case-api.git
  - repo: https://github.com/hmcts/ia-case-documents-api.git
  - repo: https://github.com/hmcts/ia-case-notifications-api.git
  - repo: https://github.com/hmcts/ia-shared-infrastructure.git
  - repo: https://github.com/hmcts/ia-aip-frontend.git
  - repo: https://github.com/hmcts/ia-timed-event-service.git
  - repo: https://github.com/hmcts/idam-api.git
  - repo: https://github.com/hmcts/idam-shared-infrastructure.git
  - repo: https://github.com/hmcts/idam-web-admin.git
  - repo: https://github.com/hmcts/idam-web-public.git
  - repo: https://github.com/hmcts/pcq-shared-infrastructure.git
  - repo: https://github.com/hmcts/pcq-consolidation-service.git
  - repo: https://github.com/hmcts/pcq-frontend.git
  - repo: https://github.com/hmcts/pcq-backend.git  
  - repo: https://github.com/hmcts/prd-pui-registration.git
  - repo: https://github.com/hmcts/probate-back-office.git
  - repo: https://github.com/hmcts/probate-business-service.git
  - repo: https://github.com/hmcts/probate-caveats-frontend.git
  - repo: https://github.com/hmcts/probate-frontend.git
  - repo: https://github.com/hmcts/probate-health-monitor.git
  - repo: https://github.com/hmcts/probate-orchestrator-service.git
  - repo: https://github.com/hmcts/probate-persistence-service.git
  - repo: https://github.com/hmcts/probate-shared-infrastructure.git
  - repo: https://github.com/hmcts/probate-submit-service.git
  - repo: https://github.com/hmcts/probatemandb.git
  - repo: https://github.com/hmcts/rd-professional-api.git
  - repo: https://github.com/hmcts/rd-user-profile-api.git
  - repo: https://github.com/hmcts/rd-profile-sync.git
  - repo: https://github.com/hmcts/rd-shared-infrastructure.git
  - repo: https://github.com/hmcts/rd-judicial-api.git
  - repo: https://github.com/hmcts/rd-judicial-data-load.git
  - repo: https://github.com/hmcts/rpa-coh-continuous-online-resolution.git
  - repo: https://github.com/hmcts/em-ccd-orchestrator.git
  - repo: https://github.com/hmcts/rpa-jui-webapp.git
  - repo: https://github.com/hmcts/rpa-professional-api.git
  - repo: https://github.com/hmcts/em-shared-infrastructure.git
  - repo: https://github.com/hmcts/rpe-pdf-service.git
  - repo: https://github.com/hmcts/rpe-shared-infrastructure.git
  - repo: https://github.com/hmcts/rpx-shared-infrastructure.git
  - repo: https://github.com/hmcts/rpx-xui-approve-org.git
  - repo: https://github.com/hmcts/rpx-xui-manage-organisations.git
  - repo: https://github.com/hmcts/rpx-xui-webapp.git
  - repo: https://github.com/hmcts/rpx-xui-terms-and-conditions.git
  - repo: https://github.com/hmcts/send-letter-service.git
  - repo: https://github.com/hmcts/service-auth-provider-app.git
  - repo: https://github.com/hmcts/snl-shared-infrastructure.git
  - repo: https://github.com/hmcts/sscs-bulk-scan.git
  - repo: https://github.com/hmcts/sscs-case-loader.git
  - repo: https://github.com/hmcts/sscs-ccd-callback-orchestrator.git
  - repo: https://github.com/hmcts/sscs-cor-backend.git
  - repo: https://github.com/hmcts/sscs-cor-frontend.git
  - repo: https://github.com/hmcts/sscs-evidence-share.git
  - repo: https://github.com/hmcts/sscs-shared-infrastructure.git
  - repo: https://github.com/hmcts/sscs-submit-your-appeal.git
  - repo: https://github.com/hmcts/sscs-track-your-appeal-frontend.git
  - repo: https://github.com/hmcts/sscs-track-your-appeal-notifications.git
  - repo: https://github.com/hmcts/sscs-tribunals-case-api.git
  - repo: https://github.com/hmcts/dg-docassembly-api.git
  - repo: https://github.com/hmcts/em-stitching-api.git
  - repo: https://github.com/hmcts/rpa-em-ccd-orchestrator.git
  - repo: https://github.com/hmcts/em-annotation-api.git
  - repo: https://github.com/hmcts/em-native-pdf-annotator-app.git
  - repo: https://github.com/hmcts/ccpay-payment-api-gateway.git
  - repo: https://github.com/hmcts/ctsc-work-allocation.git
  - repo: https://github.com/hmcts/ccpay-bulkscanning-app.git
  - repo: https://github.com/hmcts/bulk-scan-payment-processor.git
  - repo: https://github.com/hmcts/reform-scan-notification-service.git
  - repo: https://github.com/hmcts/em-icp-api.git 
  - repo: https://github.com/hmcts/camunda-bpm.git
