ccd:
  team: "CCD"
  namespace:  "ccd"
  slack:
    contact_channel: "#ccd-questions-answers"
    build_notices_channel: "#ccd-master-builds"
cmc:
  team:  "Money Claims"
  namespace:  "money-claims"
  slack:
    contact_channel: "#cmc-tech"
    build_notices_channel: "#cmc-tech-notification"
custard:
  team: "CNP"
  namespace:  "cnp"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
cet:
  team: "Civil Enforcement"
  namespace: "civil-enforcement"
  slack:
    contact_channel: "#cet-pipeline"
    build_notices_channel: "#cet-pipeline"
div:
  team: "Divorce"
  namespace: "divorce"
  slack:
    contact_channel: "#div-dev"
    build_notices_channel: "#div-dev"
dm:
  team: "Evidence Mment"
  namespace: "evidence-mment"
  slack:
    contact_channel: "#em-dev-chat"
    build_notices_channel: "#em-dev-chat"
em:
  team: "Evidence Mment"
  namespace: "evidence-mment"
  slack:
    contact_channel: "#em-dev-chat"
    build_notices_channel: "#em-dev-chat"
dg:
  team: "Evidence Mment"
  namespace: "evidence-mment"
  slack:
    contact_channel: "#em-dev-chat"
    build_notices_channel: "#em-dev-chat"
finrem:
  team: "Financial Remedy"
  namespace: "financial-remedy"
  slack:
    contact_channel: "#finrem-dev"
    build_notices_channel: "#finrem-dev"
ia:
  team: "Immigration"
  namespace: "ia"
  slack:
    contact_channel: "#ia-tech"
    build_notices_channel: "#ia-tech"
idam:
  team: "IdAM"
  namespace: "idam"
  slack:
    contact_channel: "#idam_tech"
    build_notices_channel: "#idam_tech"
fees:
  team: "Fees/Pay"
  namespace: "fees-pay"
  slack:
    contact_channel: "#cc-payments-tech"
    build_notices_channel: "#cc-payments-tech"
fees-register:
  team: "Fees/Pay"
  namespace: "fees-pay"
  slack:
    contact_channel: "#cc-payments-tech"
    build_notices_channel: "#cc-payments-tech"
payment:
  team: "Fees/Pay"
  namespace: "fees-pay"
  slack:
    contact_channel: "#cc-payments-tech"
    build_notices_channel: "#cc-payments-tech"
ccpay:
  team: "Fees/Pay"
  namespace: "fees-pay"
  slack:
    contact_channel: "#cc-payments-tech"
    build_notices_channel: "#cc-payments-tech"
bar:
  team: "Fees/Pay"
  namespace: "fees-pay"
  slack:
    contact_channel: "#bar-tech"
    build_notices_channel: "#bar-tech"
  defaultSlackChannel: "#bar-tech"
probate:
  team: "Probate"
  namespace: "probate"
  slack:
    contact_channel: "#probate"
    build_notices_channel: "#probate-jenkins"
bulk-scan:
  team: "Bulk Scanning and Printing"
  namespace: "rpe"
  slack:
    contact_channel: "#rbs"
    build_notices_channel: "#bsp-build-notices"
rpe:
  team: "Software Engineering"
  namespace: "rpe"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
core-infra:
  team: "Software Engineering"
  namespace: "rpe"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
draft-store:
  team: "Software Engineering"
  namespace: "rpe"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
pbi:
  team: "Software Engineering"
  namespace: "rpe"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
jui:
  team: "Professional Applications"
  namespace: "professional-applications"
  slack:
    contact_channel: "#jui-pipeline"
    build_notices_channel: "#jui-pipeline"
pui:
  team: "Professional Applications"
  namespace: "professional-applications"
  slack:
    contact_channel: "#pui-pipeline"
    build_notices_channel: "#pui-pipeline"
xui:
  team: "Professional Applications"
  namespace: "professional-applications"
  slack:
    contact_channel: "#xui-pipeline"
    build_notices_channel: "#xui-pipeline"
coh:
  team: "Professional Applications"
  namespace: "professional-applications"
  slack:
    contact_channel: "#coh-pipeline"
    build_notices_channel: "#coh-pipeline"
rpa:
  team: "Professional Applications"
  namespace: "professional-applications"
  slack:
    contact_channel: "#rpa-pipeline"
    build_notices_channel: "#rpa-pipeline"
rpx:
  team: "Professional Applications"
  namespace: "professional-applications"
  slack:
    contact_channel: "#xui-pipeline"
    build_notices_channel: "#xui-pipeline"
ref:
  team: "Professional Applications"
  namespace: "professional-applications"
  slack:
    contact_channel: ""
    build_notices_channel: ""
rhubarb:
  team: "CNP"
  namespace: "cnp"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
rhubarb-shared-infrastructure:
  team: "CNP"
  namespace: "cnp"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
plum:
  team: "CNP"
  namespace: "cnp"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
crumble:
  team: "CNP"
  namespace: "cnp"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
plum-shared-infrastructure:
  team: "CNP"
  namespace: "cnp"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
sscs:
  team: "SSCS"
  namespace: "sscs"
  slack:
    contact_channel: "#sscs-tech"
    build_notices_channel: "#sscs-tech"
sscs-cor:
  team: "SSCS"
  namespace: "sscs"
  slack:
    contact_channel: "#sscs-tech"
    build_notices_channel: "#sscs-tech"
sscs-tya:
  team: "SSCS"
  namespace: "sscs"
  slack:
    contact_channel: "#sscs-tech"
    build_notices_channel: "#sscs-tech"
sscs-tribunals:
  team: "SSCS"
  namespace: "sscs"
  slack:
    contact_channel: "#sscs-tech"
    build_notices_channel: "#sscs-tech"
snl:
  team: "SnL"
  namespace: "snl"
  slack:
    contact_channel: "#snl-master-builds"
    build_notices_channel: "#snl-master-builds"
am:
  team: "AM"
  namespace: "am"
  slack:
    contact_channel: "#am-master-builds"
    build_notices_channel: "#am-master-builds"
fpl:
  team: "Family Public Law"
  namespace: "family-public-law"
  slack:
    contact_channel: "#fpla-tech"
    build_notices_channel: "#fpla-tech"
ctsc:
  team: "CTSC"
  namespace: "ctsc"
  slack:
    contact_channel: "#ctsc-master-builds"
    build_notices_channel: "#ctsc-master-builds"
rd:
  team: "Reference Data"
  namespace: "rd"
  slack:
    contact_channel: "#referencedata_team"
    build_notices_channel: "#rd-master-builds"
data-extractor:
  team: "Software Engineering"
  namespace: "rpe"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
data-generator:
  team: "Software Engineering"
  namespace: "rpe"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
camunda:
  team: "Software Engineering"
  namespace: "camunda"
  slack:
    contact_channel: "#rpe"
    build_notices_channel: "#rpe-build-notices"
ethos:
  team: "Ethos Replacement"
  namespace: "ethos"
  slack:
    contact_channel: "#ethos-repl-manchester"
    build_notices_channel: "#ethos-repl-service"
azdnspoc:
  team: "DevOps"
  namespace: "azdnspoc"
  slack:
    contact_channel: "#azdnspoc-notices"
    build_notices_channel: "#azdnspoc-notices"
# The below block are unique logstash instances see ccd-logstash repo for more info
ccdprobate:
  team: "DevOps"
  namespace: "ccdprobate"
  slack:
    contact_channel: "#devops"
    build_notices_channel: "#ccd-devops"
ccdcmc:
  team: "DevOps"
  namespace: "ccdcmc"
  slack:
    contact_channel: "#devops"
    build_notices_channel: "#ccd-devops"
ccddivorce:
  team: "DevOps"
  namespace: "ccddivorce"
  slack:
    contact_channel: "#devops"
    build_notices_channel: "#ccd-devops"
ccdsscs:
  team: "DevOps"
  namespace: "ccdsscs"
  slack:
    contact_channel: "#devops"
    build_notices_channel: "#ccd-devops"
sweeper:
  team: "DevOps"
  namespace: "sweeper"
  slack:
    contact_channel: "#devops"
    build_notices_channel: "#ccd-devops"
