---
jenkins_role_yum_packages:
  - curl
  - libselinux-python
  - initscripts
  - which
  - sudo
  # from geerlingguy java dep:
  - java-1.8.0-openjdk
  # from ocha.yarn dep:
  - nodejs
  - yarn
  # from timja-kainos dep:
  - rpmdevtools
  - gettext
  - git
  - python-jenkins
