---
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Used only for Redhat installation, enables source Nginx repo.
nginx_yum_repo_enabled: true

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: false
nginx_ppa_version: stable

# The name of the nginx package to install.
nginx_package_name: "nginx"

nginx_conf_template: "nginx.conf.j2"
nginx_vhost_template: "vhost.j2"

nginx_worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

nginx_error_log: "/var/log/nginx/error.log warn"
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "65"
nginx_keepalive_requests: "100"

nginx_server_tokens: "on"

nginx_client_max_body_size: "64m"

nginx_server_names_hash_bucket_size: "64"

nginx_proxy_cache_path: ""

nginx_extra_conf_options: ""

nginx_extra_http_options: ""

nginx_remove_default_vhost: true
nginx_vhosts:
  - listen: "80"
    server_name: "{{ 'mgmtjenkins' + env + '.uksouth.cloudapp.azure.com'}}"
    filename: "{{ 'mgmtjenkins' + env + '.uksouth.cloudapp.azure.com'}}.conf"
    error_page: "403 /jenkins-on-azure"
    extra_parameters: |
      location / {
            return 301 https://$host$request_uri;
      }
  - listen: "443 ssl"
    server_name: "{{ 'mgmtjenkins' + env + '.uksouth.cloudapp.azure.com'}}"
    filename: "{{ 'mgmtjenkins' + env + '.uksouth.cloudapp.azure.com'}}-ssl.conf"
    error_page: "403 /jenkins-on-azure"
    ssl_certificate_pfx: "{{ lookup('azure_keyvault', 'secret_name=STAR-platform-hmcts-net vault_uri={{ vault_uri }}', errors='warn') }}"
    extra_parameters: |
      location / {
            proxy_pass http://localhost:8080;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_connect_timeout 150;
            proxy_send_timeout 100;
            proxy_read_timeout 100;
            proxy_buffers 4 32k;
            client_max_body_size 8m;
            client_body_buffer_size 128k;
      }
      location /cli {
             rewrite ^ /jenkins-on-azure permanent;
      }
      location /jenkins-on-azure {
             alias /usr/share/nginx/azure;
      }

nginx_upstreams: []

nginx_log_format: |
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
