---
- name: Create credentials directory
  file:
    path: "/tmp/jenkins-credentials/"
    state: directory

- include: credential.yml
  loop_control:
    loop_var: credential
  with_items:
    - "{{ jenkins_credentials }}"
  when: jenkins_credentials