---
__jenkins_repo_url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
__jenkins_repo_key_url: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
__jenkins_pkg_url: https://pkg.jenkins.io/redhat-stable
jenkins_init_file: /etc/sysconfig/jenkins
jenkins_http_port_param: JENKINS_PORT
jenkins_java_options_env_var: JENKINS_JAVA_OPTIONS


jenkins_minimum_plugins:
  - credentials
  - plain-credentials
  - credentials-binding